# Generated by Django 4.2.1 on 2023-08-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="lineapedido",
            table="linea_pedidos",
        ),
    ]
