# Generated by Django 4.2.1 on 2023-08-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_lineapedido_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="lineapedido",
            table="lineapedidos",
        ),
    ]
