# Generated by Django 4.2.1 on 2023-08-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_alter_lineapedido_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineapedido",
            old_name="pedido_id",
            new_name="pedido",
        ),
        migrations.RenameField(
            model_name="lineapedido",
            old_name="producto_id",
            new_name="producto",
        ),
    ]
