# Generated by Django 4.2.1 on 2023-08-18 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pedidos", "0004_rename_pedido_id_lineapedido_pedido_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pedidos",
            new_name="Pedido",
        ),
    ]
