# Generated by Django 4.2.1 on 2023-08-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_auto_20211009_1752"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="tienda/"),
        ),
    ]
