# Generated by Django 4.2.1 on 2023-05-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("seccion", models.CharField(max_length=20)),
                ("precio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                (
                    "direccion",
                    models.CharField(max_length=50, verbose_name="La direccion"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("fecha", models.DateField()),
                ("entregado", models.BooleanField()),
            ],
        ),
    ]
